CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50),
  due VARCHAR(12),
  level VARCHAR(10),
  description VARCHAR(100),
  status VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);